version: '3.8'

services:
  # mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    ports:
      - "33060:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
  redis:
    image: redis:latest
    container_name: micro_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
