spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:33060/micro
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: micro

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
