spring:
  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:33060/micro
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: micro

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
  port: 8000
