spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: password
  data:
    redis:
      host: localhost
      port: 6379
      password: password
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret:
    key: test_secret_key
  sql:
    init:
      mode: never
aws:
  s3:
    access-key: test-access-key
    secret-key: test-secret-key
    region: ap-northeast-2
    bucket: test-bucket
    path: test-path
