name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: kimyubi/micro_database
          stage: main
          yaml: |
            name: micro
            app: java@17
            options:
              ports: "8081"
              env:
                - name: PROFILE
                  value: prod
                - name: MICRO_DB_HOST
                  value: ${{ secrets.MICRO_DB_HOST}}
                - name: MICRO_DB_PORT
                  value: ${{ secrets.MICRO_DB_PORT}}
                - name: MICRO_DB_NAME
                  value: ${{ secrets.MICRO_DB_NAME}}
                - name: MICRO_USER_NAME
                  value: ${{ secrets.MICRO_USER_NAME}}
                - name: MICRO_PASSWORD
                  value: ${{ secrets.MICRO_PASSWORD}}          
                - name: MICRO_REDIS_HOST
                  value: ${{ secrets.MICRO_REDIS_HOST}}
                - name: MICRO_REDIS_PORT
                  value: ${{ secrets.MICRO_REDIS_PORT}}
                - name: MICRO_REDIS_PASSWORD
                  value: ${{ secrets.MICRO_REDIS_PASSWORD}}
                - name: MICRO_JWT_SECRET_KEY
                  value: ${{ secrets.MICRO_JWT_SECRET_KEY}}
                - name: MAIL_USERNAME
                  value: ${{ secrets.MAIL.USERNAME}}
                - name: MAIL_PASSWORD
                  value: ${{ secrets.MAIL.PASSWORD}}
                - name: AWS_S3_ACCESS_KEY
                  value: ${{ secrets.AWS_S3_ACCESS_KEY}}
                - name: AWS_S3_SECRET_KEY
                  value: ${{ secrets.AWS_S3_SECRET_KEY}}
                - name: AWS_S3_REGION
                  value: ${{ secrets.AWS_S3_REGION}}
                - name: AWS_S3_BUCKET
                  value: ${{ secrets.AWS_S3_BUCKET}}
                - name: AWS_S3_PATH
                  value: ${{ secrets.AWS_S3_PATH}}
                - name: ORIGIN_URL
                  value: ${{ secrets.ORIGIN_URL}}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
